############################### åŸºæœ¬ä¿¡æ¯ ###############################
info:
  name: ğ“’ğ“¸ğ“¬ğ“ªğ“’ğ“¸ğ“µğ“ª.
  docs: https://wallhaven.cc/
info1:
  name: Material-X
  docs: https://xaoxuu.com/wiki/material-x/index.html
info2:
  name: Hexo
  docs: https://hexo.io/zh-cn/
info3:
  name: TingFing
  docs: https://notebook.tingfengcloud.com/about/
  cdn: # è¦ä½¿ç”¨CDNï¼Œè¯·åœ¨æ ¹ç›®å½•çš„configæ–‡ä»¶ä¸­å†™ä¸Š use_cdn: true
    css:
      style: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.11.26/css/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.11/js/app.js
      search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.11/js/search.js
      volantis: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1.0.6/js/volantis.min.js



############################### ä¸»é¢˜é£æ ¼ ###############################
style: material    # material: å¯¼èˆªæ å’Œæ ‡é¢˜æ èƒŒæ™¯æ˜¯ä¸»é¢˜è‰²
# style: pure         # pure: å¯¼èˆªæ å’Œæ ‡é¢˜æ èƒŒæ™¯æ˜¯ç™½è‰²


############################### æœåŠ¡å¼€å…³ ###############################
scrollreveal: true
nodewaves: true
busuanzi: true
# fastclick: true



############################### é»˜è®¤å€¼ ###############################
# éŸ³ä¹æ§ä»¶çš„é»˜è®¤é…ç½®ï¼Œå¦‚æœsidebaræˆ–è€…pageé‡Œæ²¡æœ‰æä¾›ï¼Œå°±å–è¿™é‡Œçš„å‚æ•°
music:
  enable: true      # æ˜¯å¦å¯ç”¨
  color: '#1BCDFC'  # ä¸»é¢˜è‰²
  mode: circulation # random ï¼ˆéšæœºï¼‰ single ï¼ˆå•æ›²ï¼‰ circulation ï¼ˆåˆ—è¡¨å¾ªç¯ï¼‰ order ï¼ˆåˆ—è¡¨ï¼‰
  server: netease   # neteaseï¼ˆç½‘æ˜“äº‘éŸ³ä¹ï¼‰tencentï¼ˆQQéŸ³ä¹ï¼‰ xiamiï¼ˆè™¾ç±³ï¼‰ kugouï¼ˆé…·ç‹—ï¼‰
  type: playlist    # song ï¼ˆå•æ›²ï¼‰ album ï¼ˆä¸“è¾‘ï¼‰ playlist ï¼ˆæ­Œå•ï¼‰ search ï¼ˆæœç´¢ï¼‰
  id: 2615636388    # æ­Œæ›²/ä¸“è¾‘/æ­Œå• ID
  volume: 0.7       # éŸ³é‡, 0~1
  autoplay: false   # è‡ªåŠ¨æ’­æ”¾

# å‹é“¾é¡µå¤´åƒå ä½å›¾
avatar_placeholder: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/avatar/avatar.png

# æ—¥æœŸæ ¼å¼ http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # æ–‡ç« å‘å¸ƒæ—¥æœŸçš„æ ¼å¼
updated_date_format: 'll' # æ–‡ç« æ›´æ–°æ—¥æœŸçš„æ ¼å¼

# æ–‡ç« å­—æ•°ç»Ÿè®¡ã€é˜…è¯»æ—¶é•¿ï¼Œé»˜è®¤å…³é—­ï¼Œå¼€å¯éœ€è¦å®‰è£…æ’ä»¶: npm i --save hexo-wordcount
word_count: true

# å¹»ç¯ç‰‡
backstretch:
  position: full  # cover: å°é¢èƒŒæ™¯   full: æ•´ä¸ªç½‘é¡µèƒŒæ™¯
  duration: 6000 # æŒç»­æ—¶é—´ï¼ˆæ¯«ç§’ï¼‰
  fade: 2500     # æ¸å˜ï¼ˆæ¯«ç§’ï¼‰
  images:
    - /images/banner.jpg



############################### è‡ªå®šä¹‰ ###############################
# pageçš„å°é¢
cover:
  scheme: search    # åæœŸå°†ä¼šæä¾›å¤šç§å°é¢æ–¹æ¡ˆ
  #height: half      # fullï¼ˆé»˜è®¤å€¼ï¼‰: é¦–é¡µå°é¢å æ®æ•´ä¸ªç¬¬ä¸€å±å¹•ï¼Œå…¶ä»–é¡µé¢å åŠä¸ªå±å¹•é«˜åº¦ï¼Œ half: æ‰€æœ‰é¡µé¢éƒ½å°é¢éƒ½åªå åŠä¸ªå±å¹•é«˜åº¦
  title: å¬é£çš„ç¬”è®°æœ¬
  #logo: /images/head.png    # logoå’Œtitleåªæ˜¾ç¤ºä¸€ä¸ªï¼Œè‹¥åŒæ—¶è®¾ç½®ï¼Œåˆ™åªæ˜¾ç¤ºlogo
  search_placeholder: 'å¼€å¯æ–°å¤§é™†ä¹‹æ—…'
  # ä¸»é¡µå°é¢èœå•
  features:
     - name: åšæ–‡
       icon: fas fa-rss
       url: /
     - name: é¡¹ç›®
       icon: fas fa-code-branch
       url: projects/
     #- name: å‹é“¾
     #  icon: fas fa-link
     #  url: friends/
     # rel: nofollow
     - name: å…³äº
       icon: fas fa-info-circle
       url: about/
       rel: nofollow
     - name: playlist
       icon: fas fa-headphones-alt
       url: playlist/
       rel: nofollow


# æ¡Œé¢ç«¯å¯¼èˆªæ èœå•
menu_desktop:
  # - name: åˆ†ç±»
  #   icon: fas fa-folder-open
  #   url: /categories/
  #   rel: nofollow
  - name: æ ‡ç­¾
    icon: fas fa-hashtag
    url: /tags/
    rel: nofollow
  - name: å½’æ¡£
    icon: fas fa-archive
    url: /archives
    rel: nofollow
  - name: æ­Œå•
    icon: fas fa-headphones-alt
    url: /playlist
    rel: nofollow
  

menu:
  home: / || home
  categories: /categories/ || th
  tags: /tags/ || tags
  archives: /archives/ || archive
  playlist: /playlist/ || music
  about: /about/ || user
  

# æ‰‹æœºç«¯å¯¼èˆªèœå•ï¼ˆä»å³ä¸Šè§’çš„æŒ‰é’®ç‚¹å‡»å±•å¼€ï¼‰
menu_mobile:
  - name: è¿‘æœŸæ–‡ç« 
    icon: fas fa-clock
    url: /
  - name: æ–‡ç« å½’æ¡£
    icon: fas fa-archive
    url: /archives/
    rel: nofollow
  # - name: å¼€æºé¡¹ç›®
  #   icon: fas fa-code-branch
  #   url: projects/
  # - name: æˆ‘çš„å‹é“¾
  #   icon: fas fa-link
  #   url: friends/
  #   rel: nofollow
  # - name: ä¸»é¢˜æ–‡æ¡£
  #   icon: fas fa-book
  #   url: https://xaoxuu.com/wiki/material-x/
  #   rel: nofollow
  - name: å…³äºå°ç«™
    icon: fas fa-info-circle
    url: about/
    rel: nofollow

layout:
  # æ–‡ç« åˆ—è¡¨ï¼ˆä¸»é¡µã€è‡ªå®šä¹‰çš„åˆ—è¡¨ï¼‰å¸ƒå±€
  posts:
    # åˆ—è¡¨ä¸­æ¯ä¸€ç¯‡æ–‡ç« çš„metaä¿¡æ¯
    meta: [title, author, date, categories, wordcount, top]
    # åˆ—è¡¨ç±»é¡µé¢çš„ä¾§è¾¹æ 
    sidebar: [author, plain, list, grid, category, tagcloud]
  # æ–‡ç« é¡µé¢å¸ƒå±€
  article:
    # æ–‡ç« é¡µé¢ä¸»ä½“å…ƒç´ ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨é¡µé¢çš„Front-matterä¸­è®¾ç½®
    body: [article, comments]
    # é»˜è®¤çš„metaä¿¡æ¯ï¼Œæ–‡ç« ä¸­æ²¡æœ‰é…ç½®åˆ™æŒ‰ç…§è¿™é‡Œçš„é…ç½®æ¥æ˜¾ç¤ºï¼Œè®¾ç½®ä¸ºfalseåˆ™ä¸æ˜¾ç¤º
    # å…¶ä¸­ï¼Œtitleåªåœ¨headerä¸­æœ‰æ•ˆï¼Œmusicå’Œthumbnailæ— éœ€åœ¨è¿™é‡Œè®¾ç½®ï¼Œæ–‡ç« ä¸­æœ‰åˆ™æ˜¾ç¤º
    # å¦‚æœtagsæ”¾ç½®åœ¨meta.headerä¸­ï¼Œé‚£ä¹ˆåœ¨poståˆ—è¡¨ä¸­ä¸æ˜¾ç¤ºï¼ˆå› ä¸ºå¡ç‰‡ä¸‹æ–¹å·²ç»æœ‰äº†ï¼‰
    header: [title, author, date, categories, counter, wordcount, top]
    footer: [updated, tags, share]
    # æ–‡ç« é¡µé¢çš„ä¾§è¾¹æ 
    sidebar: [author, plain, toc, grid, category, tagcloud, list, related_posts]
  # å…¶ä»–çš„é¡µé¢å¸ƒå±€æš‚æ—¶ç­‰äºæ–‡ç« åˆ—è¡¨


# ä¾§è¾¹æ å°éƒ¨ä»¶é…ç½®
sidebar:
  - widget: author
    avatar: images/head.png
    jinrishici: true
    social: true
  - widget: toc
  - widget: grid
    icon: fas fa-map-signs
    title: ç«™å†…å¯¼èˆª
    rows:
      - name: è¿‘æœŸæ–‡ç« 
        icon: fas fa-clock
        url: /
      - name: æ–‡ç« å½’æ¡£
        icon: fas fa-archive
        url: /archives/
        rel: nofollow
  - widget: tagcloud
    icon: fas fa-tags
    more:
      icon: fas fa-expand-arrows-alt
      url: /tags/
      rel: nofollow
  - widget: plain
    icon: fas fa-handshake 
    title: "åˆ†åˆ†é’Ÿæ‰¾åˆ°ä½ "
    body: <script src="https://pv.sohu.com/cityjson?ie=utf-8"></script>
          <script>var getOSAndBrowser=function(){var os=navigator.platform;var userAgent=navigator.userAgent;var info="";var tempArray="";if(os.indexOf("Win")>-1){if(userAgent.indexOf("Windows NT 5.0")>-1){info+="Win2000"}else if(userAgent.indexOf("Windows NT 5.1")>-1){info+="WinXP"}else if(userAgent.indexOf("Windows NT 5.2")>-1){info+="Win2003"}else if(userAgent.indexOf("Windows NT 6.0")>-1){info+="WindowsVista"}else if(userAgent.indexOf("Windows NT 6.1")>-1||userAgent.indexOf("Windows 7")>-1){info+="Win7"}else if(userAgent.indexOf("Windows NT 6.2")>-1||userAgent.indexOf("Windows 8")>-1){info+="Win8"}else if(userAgent.indexOf("Windows NT 6.3")>-1||userAgent.indexOf("Windows 8.1")>-1){info+="Win8.1"}else if(userAgent.indexOf("Windows NT 10.0")>-1||userAgent.indexOf("Windows 10")>-1){info+="Win10"}else{info+="Other"}}else if(os.indexOf("Mac")>-1){info+="Mac"}else if(os.indexOf("X11")>-1){info+="Unix"}else if(os.indexOf("Linux")>-1){info+="Linux"}else{info+="Other"}info+="/";var isOpera=userAgent.indexOf("Opera")>-1;var isIE=userAgent.indexOf("compatible")>-1&&userAgent.indexOf("MSIE")>-1&&!isOpera;var isEdge=userAgent.toLowerCase().indexOf("edge")>-1&&!isIE;var isIE11=(userAgent.toLowerCase().indexOf("trident")>-1&&userAgent.indexOf("rv")>-1);if(/[Ff]irefox(\/\d+\.\d+)/.test(userAgent)){tempArray=/([Ff]irefox)\/(\d+\.\d+)/.exec(userAgent);info+=tempArray[1]+tempArray[2]}else if(isIE){var version="";var reIE=new RegExp("MSIE (\\d+\\.\\d+);");reIE.test(userAgent);var fIEVersion=parseFloat(RegExp["$1"]);if(fIEVersion==7){version="IE7"}else if(fIEVersion==8){version="IE8"}else if(fIEVersion==9){version="IE9"}else if(fIEVersion==10){version="IE10"}else{version="0"}info+=version}else if(isEdge){info+="Edge"}else if(isIE11){info+="IE11"}else if(/[Cc]hrome\/\d+/.test(userAgent)){tempArray=/([Cc]hrome)\/(\d+)/.exec(userAgent);info+=tempArray[1]+tempArray[2]}else if(/[Vv]ersion\/\d+\.\d+\.\d+(\.\d)* *[Ss]afari/.test(userAgent)){tempArray=/[Vv]ersion\/(\d+\.\d+\.\d+)(\.\d)* *([Ss]afari)/.exec(userAgent);info+=tempArray[3]+tempArray[1]}else if(/[Oo]pera.+[Vv]ersion\/\d+\.\d+/.test(userAgent)){tempArray=/([Oo]pera).+[Vv]ersion\/(\d+)\.\d+/.exec(userAgent);info+=tempArray[1]+tempArray[2]}else{info+="unknown"}return info};document.write("æ¬¢è¿,æ¥è‡ª"+returnCitySN["cname"]+"çš„æœ‹å‹");document.write("<br>æ‚¨çš„ip:"+returnCitySN["cip"]);document.write("<br>æ‚¨ä½¿ç”¨çš„æ˜¯"+getOSAndBrowser());</script>
  



# ç¤¾äº¤ä¿¡æ¯
social:
  # - icon: fas fa-rss
  #   url: atom.xml
  - icon: fas fa-envelope
    url: mailto:18649325562@163.com
  - icon: fas fa-headphones-alt
    url: https://music.163.com/#/my/m/music/playlist?id=866897563
  - icon: fab fa-zhihu
    url: https://www.zhihu.com/people/fu-gui-tianzhong-qiu/activities
  - icon: fab fa-weixin
    url: https://lol.qq.com/main.shtml


# åˆ†äº«æŒ‰é’®
# å½“idä¸ºqrcodeæ—¶éœ€è¦å®‰è£…æ’ä»¶  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQå¥½å‹
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQç©ºé—´
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  # - id: qrcode
  #   name: å¾®ä¿¡
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: å¾®åš
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  # - id: qrcode
  #   name: QRcode
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png


footer_post: 'day day up'
# footer: 'ç½‘é¡µé¡µè„šæ–‡å­—ï¼Œæ”¯æŒ[markdown](/)'


############################### è¯„è®ºç³»ç»Ÿ ###############################
# disqus_shortname: è¦ä½¿ç”¨å“ªä¸ªè¯·å¤åˆ¶åˆ°æ ¹ç›®å½•é…ç½®æ–‡ä»¶ï¼
# livere_uid: è¦ä½¿ç”¨å“ªä¸ªè¯·å¤åˆ¶åˆ°æ ¹ç›®å½•é…ç½®æ–‡ä»¶ï¼
# gitalk: è¦ä½¿ç”¨å“ªä¸ªè¯·å¤åˆ¶åˆ°æ ¹ç›®å½•é…ç½®æ–‡ä»¶ï¼
#   clientID: ä½ çš„clientID
#   clientSecret: ä½ çš„clientSecret
#   repo: ä½ çš„repoå
#   owner: ä½ çš„GitHubå
#   admin: [] è‡³å°‘å¡«å†™ä½ çš„GitHubå
# leancloud: è¦ä½¿ç”¨å“ªä¸ªè¯·å¤åˆ¶åˆ°æ ¹ç›®å½•é…ç½®æ–‡ä»¶ï¼
#   app_id: ä½ çš„appId
#   app_key: ä½ çš„appKey


############################### æ‚é¡¹ï¼Œè¯·å‹¿åˆ é™¤ ###############################
#valineé…ç½®
valine:
  enable: true # å¦‚æœä½ æƒ³ç”¨Valineè¯„è®ºç³»ç»Ÿï¼Œè¯·è®¾ç½®enableä¸ºtrue
  volantis: true # æ˜¯å¦å¯ç”¨volantisç‰ˆæœ¬ï¼ˆç¦æ­¢åŒ¿åï¼Œå¢åŠ è‹¥å¹²è´´å§ã€QQè¡¨æƒ…ï¼‰
  # è¿˜éœ€è¦åœ¨æ ¹ç›®å½•é…ç½®æ–‡ä»¶ä¸­æ·»åŠ ä¸‹é¢è¿™ä¸‰è¡Œå†…å®¹
  # leancloud:
  #   app_id: ä½ çš„appId
  #   app_key: ä½ çš„appKey
  guest_info: nick,mail #valine comment header info
  placeholder: å¿«æ¥è¯„è®ºå§~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# æœç´¢é…ç½®
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Lessæ¸²æŸ“
less:
  compress: true

#ç»Ÿè®¡
cnzz: true

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
live2d:
  enable: true
  #enable: false
  scriptFrom: local # é»˜è®¤
  pluginRootPath: live2dw/ # æ’ä»¶åœ¨ç«™ç‚¹ä¸Šçš„æ ¹ç›®å½•(ç›¸å¯¹è·¯å¾„)
  pluginJsPath: lib/ # è„šæœ¬æ–‡ä»¶ç›¸å¯¹ä¸æ’ä»¶æ ¹ç›®å½•è·¯å¾„
  pluginModelPath: assets/ # æ¨¡å‹æ–‡ä»¶ç›¸å¯¹ä¸æ’ä»¶æ ¹ç›®å½•è·¯å¾„
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # ä½ çš„è‡ªå®šä¹‰ url
  tagMode: false # æ ‡ç­¾æ¨¡å¼, æ˜¯å¦ä»…æ›¿æ¢ live2d tagæ ‡ç­¾è€Œéæ’å…¥åˆ°æ‰€æœ‰é¡µé¢ä¸­
  debug: false # è°ƒè¯•, æ˜¯å¦åœ¨æ§åˆ¶å°è¾“å‡ºæ—¥å¿—
  model:
    use: live2d-widget-model-z16
    # use: live2d-widget-model-wanko # npm-module package name
    # use: wanko # åšå®¢æ ¹ç›®å½•/live2d_models/ ä¸‹çš„ç›®å½•å
    # use: ./wives/wanko # ç›¸å¯¹äºåšå®¢æ ¹ç›®å½•çš„è·¯å¾„
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # ä½ çš„è‡ªå®šä¹‰ url
  display:
    position: right
    width: 145
    height: 340
  mobile:
    show: true # æ˜¯å¦åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šæ˜¾ç¤º
    scale: 0.5 # ç§»åŠ¨è®¾å¤‡ä¸Šçš„ç¼©æ”¾
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.8



aplayer:
  meting: true
